import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { useState, useEffect } from 'react';
import { API } from 'aws-amplify';
import { listPosts } from './../src/graphql/queries';
export default function Home() {
	const [posts, setPosts] = useState([]);

	useEffect(() => {
		fetchPosts();
	});
	async function fetchPosts() {
		const postData = await API.graphql({ query: listPosts });
		const postsFromAPI = postData.data.listPosts.items;
		setPosts(postsFromAPI);
	}
	return (
		<div className="bg-grey">
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div>
				{posts.map((post,index) => (
						<h1 key={index}>{post.content}</h1>
				))}
			</div>
		</div>
	);
}
